name: 📦🚀 CI


on:
  push:
    branches:
      - '**'


permissions:
  contents: write
  pull-requests: write


env:
  DEFAULT_PYTHON_VERSION: '3.11'
  DEFAULT_POETRY_VERSION: '1.6.0'



jobs:
  validation:
    name: 🧪 Validation
    if: ${{ !contains(github.event.head_commit.message, 'chore(main)') }}  # don't run on chore(main) commits (e.g. release - it already ran)
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ github.ref == 'refs/heads/main' && fromJson('["3.8", "3.9", "3.10", "3.11"]') || fromJson('["default"]') }}
        os: ${{ github.ref == 'refs/heads/main' && fromJson('["ubuntu-latest", "macos-latest", "windows-latest"]') || fromJson('["ubuntu-latest"]') }}

    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      issues: none
      pull-requests: none
      id-token: write


    steps:
      - uses: actions/checkout@v4

      - uses: corriander/gha/poetry/test@main
        with:
          python-version: ${{ matrix.python-version == 'default' && env.DEFAULT_PYTHON_VERSION || matrix.python-version }}
          poetry-version: ${{ env.DEFAULT_POETRY_VERSION }}

  release:
    name: 🚀 Release
    runs-on: ubuntu-latest
    needs: validation
    if: |  # always run on default branch as long as no failures, even if validation is skipped
      always()
      && !contains(needs.*.result, 'failure')
      && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: python
          package-name: vdd

      - uses: actions/checkout@v4

      - uses: corriander/gha/poetry/publish@main
        if: steps.release.outputs.release_created
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
          poetry-version: ${{ env.DEFAULT_POETRY_VERSION }}
          release-tag: ${{ steps.release.outputs.tag_name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pypi-token: ${{ secrets.PYPI_TOKEN }}
          dynamic-versioning: false
